### ISSUE TITLE
Error in npm run production 

### ISSUE THREAD

**Issue by renattonl** [inertiajs/inertia-vue#69]
In development mode everything works fine. The problem is when you deploy.

`npm run production`

result: 

```console
> @ production /home/node/app
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/w
ebpack.config.js

CssSyntaxError: /css/app.css:1:1: Unknown word
    at Input.error (/home/node/app/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/home/node/app/node_modules/postcss/lib/parser.js:563:22)
    at Parser.other (/home/node/app/node_modules/postcss/lib/parser.js:168:12)
    at Parser.parse (/home/node/app/node_modules/postcss/lib/parser.js:77:16)
    at parse (/home/node/app/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/home/node/app/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/home/node/app/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/home/node/app/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/home/node/app/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/home/node/app/node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
    at Object.processor (/home/node/app/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
    at each (/home/node/app/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/home/node/app/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/home/node/app/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/home/node/app/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/home/node/app/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _next0 (eval at create (/home/node/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:17)
    at _err0 (eval at create (/home/node/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at taskRunner.run (/home/node/app/node_modules/terser-webpack-plugin/dist/index.js:321:9)
    at step (/home/node/app/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at _cacache.default.get.then (/home/node/app/node_modules/terser-webpack-plugin/dist/TaskRunner.js:111:15)
    at tryCatcher (/home/node/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/node/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/node/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/node/app/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/home/node/app/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/home/node/app/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/home/node/app/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/home/node/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/node/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/node/app/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/home/node/app/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/home/node/app/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/home/node/app/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/home/node/app/node_modules/bluebird/js/release/promise.js:574:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-08-15T16_19_37_864Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-08-15T16_19_37_889Z-debug.log
```

My package.json:

```json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --disable-host-check --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "page-dev": "npm run page-development --",
    "page-development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.mix.page.js",
    "page-watch": "npm run page-development -- --watch",
    "page-watch-poll": "npm run watch -- --watch-poll",
    "page-hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.mix.page.js",
    "page-prod": "npm run page-production --",
    "page-production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.mix.page.js"
  },
  "dependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@inertiajs/inertia": "^0.1.3",
    "@inertiajs/inertia-vue": "^0.1.1",
    "axios": "^0.19.0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.27",
    "ckeditor": "^4.9.2",
    "font-awesome": "^4.7.0",
    "intro.js": "^2.9.3",
    "jquery": "^3.4.1",
    "jquery-contextmenu": "^3.0.0-beta.2",
    "jquery-datetimepicker": "^2.5.21",
    "local-storage": "^1.4.2",
    "lodash": "^4.17.15",
    "popper.js": "^1.14.3",
    "ractive": "^0.10.14",
    "sweetalert2": "^7.21.1",
    "toastr": "^2.1.4",
    "validate.js": "^0.12.0",
    "vee-validate": "^2.1.7",
    "vue": "^2.6.10",
    "vue-sweetalert2": "^2.1.1",
    "vue-toastr": "^2.0.16",
    "vuejs-datepicker": "^1.5.4",
    "vuex": "^3.1.1",
    "vuex-map-fields": "^1.3.4"
  },
  "devDependencies": {
    "clean-webpack-plugin": "^2.0.2",
    "compression-webpack-plugin": "^2.0.0",
    "cross-env": "^5.2.0",
    "laravel-mix": "^4.1.2",
    "ractive-bin-loader": "^1.0.2",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.22.9",
    "sass-loader": "^7.2.0",
    "vue-template-compiler": "^2.6.10"
  }
}
```

My webpack.mix.js

```javascript
const mix = require('./configJS/configWebpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const path = require('path')

mix.customConfig.plugins.push(
  new CleanWebpackPlugin({
    cleanOnceBeforeBuildPatterns: [
      'css', 'fonts', 'images' , 'js', 'ckeditor',
    ],
  }),
)

mix.customConfig.output = { chunkFilename: 'js/[name].js?id=[chunkhash]' }
mix.customConfig.resolve = {
  alias: {
    vue$: 'vue/dist/vue.runtime.esm.js',
    '@': path.resolve('resources/js'),
  },
}

mix.webpackConfig(mix.customConfig)

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .sass('resources/sass/vendor.scss', 'public/css')
    .sass('resources/sass/sidebar.scss', 'public/css')
    .scripts(['node_modules/ckeditor/ckeditor.js'], 'public/ckeditor/ckeditor.js')
    .scripts(['node_modules/ckeditor/config.js'], 'public/ckeditor/config.js')
    .scripts(['node_modules/ckeditor/styles.js'], 'public/ckeditor/styles.js')
    .styles(['node_modules/ckeditor/contents.css'], 'public/ckeditor/contents.css')
    .copyDirectory('node_modules/ckeditor/adapters', 'public/ckeditor/adapters')
    .copyDirectory('node_modules/ckeditor/lang/es.js', 'public/ckeditor/lang/es.js')
    .copyDirectory('node_modules/ckeditor/plugins', 'public/ckeditor/plugins')
    .copyDirectory('node_modules/ckeditor/skins', 'public/ckeditor/skins')
    .copyDirectory('resources/assets/images', 'public/images');

```
My app.scss is simple:

```sass
.modal{
  z-index: 1000000;
}
.toast-container {
  z-index: 1000001;
}

.modal-lg{
  width: 90%;
}

@media (min-width: 992px)
{
  .modal-lg {
    max-width: 90%;
  }
}

.nav-item{
  padding: 6px 0;
}

.pointer{
  cursor: pointer;
}

h4.title {
  margin-top: 0;
  background-color: #3b5998;
  color: #fff;
  border-radius: 5px 5px 0 0;
  margin-bottom: 0;
  padding: 10px 0;
}


.footer{
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 56px;
  background-color: #bbb;
  line-height: 55px;
}

```

My vendor.scss:

```sass
// Variables
@import 'variables';

@import '~bootstrap/scss/bootstrap';
@import '~bootstrap-vue/dist/bootstrap-vue.css';
@import '~font-awesome/scss/font-awesome.scss';
@import '~vue-toastr/src/vue-toastr.scss';
@import 'sweetalert2/src/sweetalert2';
@import "./bootstrap-4-navbar";
@import './pageLoader';

```

When I comment on the following and run `npm run prod`, it works.

```javascript
mix.js('resources/js/app.js', 'public/js')
    // .sass('resources/sass/app.scss', 'public/css')
    // .sass('resources/sass/vendor.scss', 'public/css')
    // .sass('resources/sass/sidebar.scss', 'public/css')
    .scripts(['node_modules/ckeditor/ckeditor.js'], 'public/ckeditor/ckeditor.js')
    .scripts(['node_modules/ckeditor/config.js'], 'public/ckeditor/config.js')
    .scripts(['node_modules/ckeditor/styles.js'], 'public/ckeditor/styles.js')
    .styles(['node_modules/ckeditor/contents.css'], 'public/ckeditor/contents.css')
    .copyDirectory('node_modules/ckeditor/adapters', 'public/ckeditor/adapters')
    .copyDirectory('node_modules/ckeditor/lang/es.js', 'public/ckeditor/lang/es.js')
    .copyDirectory('node_modules/ckeditor/plugins', 'public/ckeditor/plugins')
    .copyDirectory('node_modules/ckeditor/skins', 'public/ckeditor/skins')
    .copyDirectory('resources/assets/images', 'public/images');
```

**Comment by Juhlinus** [comment]
@renattonl What does your app.scss look like?

Judging from your error it looks like some kind of syntax error related to SASS, and probably not related to InertiaJS.

**Comment by renattonl** [comment]
@Juhlinus  I just updated the issue.

**Comment by renattonl** [comment]
@Juhlinus  if i convert my app.scss file to app.css and change the line `.sass('resources/sass/app.scss', 'public/css')` to `.styles(['resources/sass/app.css'], 'public/css/app.css')` ....This works.

**Comment by Juhlinus** [comment]
@renattonl Have a look at this issue:
https://github.com/webpack-contrib/css-loader/issues/163

Again, I don't believe this to be related to Inertia-Vue, so you'd probably be better off checking out some laravel mix and webpack documentation.

**Comment by renattonl** [comment]
ok @Juhlinus  thank's!

**Comment by reinink** [comment]
Closing this, since it doesn't look like an issue with Inertia.

Good luck @renattonl. 💪 

Thanks for helping out here @Juhlinus! 🙌

**Comment by abhisheksarmah** [comment]
if you have issues regarding npm run production with scss and laravel-mix.
The error showing is CssSyntaxError:` /css/app.css:58472:13: Missed semicolon

Please follow this link, 
https://github.com/JeffreyWay/laravel-mix/issues/1982#issuecomment-484284092
