### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by emmannl** [inertiajs/inertia-vue#97]
I have an installation of Laravel 6 with vue.
I'm trying to use inertiajs, but I'm unable to run `npm run dev` successfully.
I always get this error:
`TypeError: Cannot read property 'startsWith' of undefined`

I'm following the exact step at https://inertiajs.com/client-side-setup
and my `resources/app.js` is exactly as in the docs.

Now, if I comment the line :
`resolveComponent: name => require(`./Pages/${name}`).default,
`
`npm run dev` completes successfully. What could be wrong?

Here's a full error trace
`
npm run dev

> @ dev /home/emman/Projects/pwd
> npm run development

> @ development /home/emman/Projects/pwd
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 1 errors                       10:39:47 PM

TypeError: Cannot read property 'startsWith' of undefined
    at isRelative (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:5:17)
    at Array.from.map.module (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:64:15)
    at Array.map (<anonymous>)
    at groupModules (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:62:43)
    at formatErrors (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:74:18)
    at format (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js:87:10)
    at format (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:12:33)
    at Array.map (<anonymous>)
    at formatErrors (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/core/formatErrors.js:15:21)
    at FriendlyErrorsWebpackPlugin.displayErrors (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:110:5)
    at doneFn (/home/emman/Projects/pwd/node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:51:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/emman/Projects/pwd/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/emman/Projects/pwd/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:485:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/emman/Projects/pwd/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/home/emman/Projects/pwd/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:482:27)
    at /home/emman/Projects/pwd/node_modules/neo-async/async.js:2818:7
    at done (/home/emman/Projects/pwd/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/emman/Projects/pwd/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/home/emman/Projects/pwd/node_modules/webpack/lib/Compiler.js:464:33)
    at /home/emman/Projects/pwd/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emman/.npm/_logs/2019-10-10T21_39_47_848Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: npm run development
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by hawezo** [comment]
Looks like an import error. Do you have that `Pages` directory?

**Comment by emmannl** [comment]
I thought that might be the reason, so I created the `Pages` directory, error still persists

**Comment by emmannl** [comment]
Apparently, I created the `Pages` folder in a wring place, all good now.

**Comment by marvinhosea** [comment]
This is not mentioned in docs?
